language: ruby
rvm:
- 2.2
sudo: false
addons:
  postgresql: "9.3"
before_script:
- psql -c 'create database event_store_test;' -U postgres
script: bundle exec rspec spec
env:
  global:
    secure: TwtWLZbhiu6kjGMOSq4nEj6t2tg/vD8KSIh7AzS3Pu9dl/uvSgJ91Xjv0xSC+j71EddXSwOsKYut7q0SP3qA4KMB1YGicTu6JQadO0gfy16EJobatAUUorS9gWfA2xgO1kcj0eoCqHbnJFML30AdrvDlZ9rrzb/Kb6gZKfgcRJo=
  matrix:
    - DB_CONFIG=spec/support/database_postgres.yml
    - DB_CONFIG=spec/support/database_sqlite.yml
